### ISSUE TITLE
Installing the kernel driver fails if UAC is set to the highest setting

### ISSUE THREAD

**Issue by NoriLynnfield** [SpecialKO/SKIF#10]
[Bug encountered with SKIF 0.9.11 on Windows 11 build 22621]

Trying to install the kernel driver fails if your windows installation has User Account conrtrol set to its highest setting:

The error: ![image](https://user-images.githubusercontent.com/28459742/222927806-5ce63511-ecab-4847-8bfd-73b1855ac910.png) 

UAC setting that causes the error: 
![image](https://user-images.githubusercontent.com/28459742/222927895-ebf3b9ab-b059-43f7-aa44-f4cbd774ed8d.png)

Turning the UAC down 1 level allowed successful installation of the kernel driver; this may just be a coincidence, but I don't think it is.

**Comment by Aemony** [comment]
Thanks for reporting this issue! It seems that the logic within Special K itself `SpecialK64.dll` which handles this whole process removes the `Installer64.dll` file before the user actually have been able to approve the elevation request.

So what happens is basically:

1. SKIG loads `SpecialK64.dll` and calls its `SK_WinRing0_Install` function.
2. `Installer64.dll` is created to facilitate the final driver installation process.
3. UAC is triggered to elevate the permissions to the necessary ones for `Installer64.dll` to do its thing.
4. `Installer64.dll` finalizes the installation of the driver.
5. `SpecialK64.dll` removes the `Installer64.dll` file again since it has done its job.

The issue seems to occur on step 3, when UAC is triggered.

In terms of security, UAC effectively only has [two distinct settings](https://devblogs.microsoft.com/oldnewthing/20160816-00/?p=94105) on its slider -- **Always notify** and as Microsoft puts it **"Meh"**.  All three bottom settings enables an auto elevation feature that allows UAC to silently approve elevation requests if the caller is from a trusted process.

As I understand it Microsoft provides a way for COM/driver/etc to utilize that behaviour to faciliate installs in some scenarios. Special K made use of this as the driver could initially only be installed/uninstalled from within a game where a separate UAC prompt would cause havoc.

So it seems that the internal proceedure of `SpecialK64.dll` simply does not wait long enough before it removes the `Installer64.dll`. If the auto elevation process is successful (which it will be with UAC on any of the three bottom settings), then the installation proceeds normally, and the installer DLL file is removed at the end, but if UAC is set to the highest (no auto elevation allowed), then the installer DLL file gets removed before the user have been able to approve the elevation.

I'll see if we can redo this design somewhat. I'm personally not really glad to see this all stuffed in the `SpecialK64.dll` file itself and would much rather see it handled through a discrete `SKIFdrv.exe` that also allows installing/uninstalling the driver without the main components of SKIF or SK involved.

**Comment by Kaldaien** [comment]
The reason this logic is stuffed into SpecialK64.dll is to prevent installing the driver on a system that can't load the driver because of missing dependencies. If you're going to build a standalone tool, it needs to have the same DLL dependencies as the driver and SK.

It would make more sense to just create the `SKIFdrv.exe` thing and have it load SK's DLL and run the appropriate commands (AFTER) UAC prompt runs. RunDLL can't do this because of DOS 8.3 filenames. This still retains the property that if SK's DLL can't be loaded, the driver also won't be installed. Which is very important.

**Comment by Aemony** [comment]
https://github.com/SpecialKO/SKIFdrv have been created, and an installer for it is currently being tested on the Discord.

You can download a copy of the installer here: 
https://cdn.discordapp.com/attachments/792979353117524009/1082737657559384195/redist_SK_WinRing0.exe

SKIF will soon be updated to make calls to SKIFdrv, which then handles the installation or uninstallation of the driver.

**Comment by Aemony** [comment]
This was resolved through the creation of the separate driver package:
https://wiki.special-k.info/en/SpecialK/Tools#extended-hardware-monitoring-driver
