### ISSUE TITLE
Favorites Group is always folded-in on every startup of the SKIF app

### ISSUE THREAD

**Issue by audaki** [SpecialKO/SKIF#30]
Favorites Group is always folded-in on every startup of the SKIF app

![image](https://github.com/SpecialKO/SKIF/assets/1321285/8127b053-e89b-4082-866b-1cd806289840)

![image](https://github.com/SpecialKO/SKIF/assets/1321285/f8bf5362-8551-4591-a661-93905d1a2e0d)

**Comment by Aemony** [comment]
This is by design. The only category that will be expanded upon launch is the one that has the last selected game (requires that setting to be enabled, see Settings -> Library -> Remember the last selected game).

If you want a game to always be easily accessible regardless of the last selected game, right click the game and click on **Manage -> Favorite (pinned; max 5)** as this will pin it in a separate "pinned favorites" area above the rest of the list of games.

**Comment by Aemony** [comment]
> I can mention that long-term SKIF will probably be able to track and remember the collapse state of categories between sessions

This was implemented recently and should be available in the latest version of SKIF.
