### ISSUE TITLE
UI modes other than, "Safe Mode", trigger VRR When MPOs are enabled

### ISSUE THREAD

**Issue by MaceYaFace** [SpecialKO/SKIF#32]
Under the latest version of SKIF, the UI modes, "VRR Compatibility", and, "Normal", trigger VRR at either ~58Hz if MPOs are active. Disabling MPOs fixes this behaviour and the refresh rate remains at the display's highest. "Safe mode", does not exhibit this behaviour.

**Comment by Aemony** [comment]
Please ensure you don't have a v-sync override enforced for all apps (or SKIF) in the display drivers.

The VRR Compatibility mode uses a v-sync presentation interval of `2` as this is necessary to disallow MPO VRR to engage.

If for example the display drivers enforces v-sync ON *or* OFF then SKIF's VRR Compatibility mode will be unable to function properly and VRR will instead engage.

**Comment by Aemony** [comment]
Nvidia users can also try using the `Disable GFE notifications` button in Settings -> Advanced once and then restart SKIF. I forgot if it forcefully disabled VRR for SKIF or not, but it's definitely worth a shot.

Note that SKIF is unable to check the state of it so only use the button once.

**Comment by MaceYaFace** [comment]
I don't run GFE, however disabling VSync for SKIF in the NVCP worked. Behaviour is as expected now, where VRR compatible mode is not activating VRR and Normal mode is.

Though this only became an issue once I had updated SKIF form the latest installer build to the latest nightly. Might be worth looking into.

**Comment by Aemony** [comment]
There is nothing different in that regard in the latest version -- it works the same as the previous version. This has always been a known issue that's outside of our control since, well, the display drivers are working as intended and overrides our configured behavior.

The only actual thing that could cause a change in behavior is a change in the display drivers, such as a reset of the driver profiles.

Btw, the GFE button isn't only for GFE users. The two settings it changes resides in the Nvidia display driver profile for SKIF.exe, and so whether the user has GFE or not is irrelevant as the two driver profile flags it sets can be set regardless.

One of them disables GFE for SKIF. The other (if I remember it right) disables VRR for SKIF. Each Special K installer also actually runs this call automatically but silently, which reinforces one of the settings (the VRR one I think; the other requires elevation to be applied).
